language: php
php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
- composer install

script:
- ./vendor/bin/phpstan analyse --level 7 src
- ./vendor/bin/phpunit
- ./vendor/bin/infection --min-msi=75 --min-covered-msi=75
